project:
  type: website
  output-dir: docs

website:
  site-url: "https://ayelbatac.github.io"
  navbar:
    title: "<a href='index.html' style='display: flex; align-items: center; gap: 0.5rem; text-decoration: none; color: white;'>
              <img src='logo.png' alt='Logo' style='height: 60px;'>
              <strong>Ayel L. R. Batac</strong>
            </a>"
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Research"
        href: research.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Knowledge Translation"
        menu:
          - text: "Infographics"
            href: infographics.qmd
          - text: "Blog"
            href: blog.qmd
          - text: "Talks and Presentations"
            href: talks.qmd
      - text: "Contact"
        href: contact.qmd

  page-footer:
    center: "Â© 2025 Ayel L. R. Batac. All Rights Reserved."

format:
  html:
    css: styles.css
    anchor-links: false
    include-in-header: meta.html
